# Makefile for stt_tts
# Generated by Turn.io Lua SDK

IMAGE := ghcr.io/turnhub/turn-lua-sdk:latest

.PHONY: help test watch build clean

help: ## Show this help message
	@echo "stt_tts - Turn.io Lua App"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

test: ## Run tests
	@docker run --rm -v $$(pwd):/workspace $(IMAGE) turn-app test

watch: ## Watch mode - auto-run tests on file changes
	@docker run --rm -v $$(pwd):/workspace $(IMAGE) turn-app watch

build: ## Build ZIP for deployment
	@docker run --rm -v $$(pwd):/workspace $(IMAGE) turn-app build

clean: ## Remove built ZIP files
	@rm -f *.zip

shell: ## Open shell in container
	@docker run --rm -it -v $$(pwd):/workspace $(IMAGE) /bin/sh
